---
- name: Using standard system facts demo
  hosts: servera.lab.example.com
  gather_facts: no
  tasks:
  - name: Display the hostname collected by setup
    debug:
     msg: "The server name fact collected from the hosts: {{ansible_hostname}}'"
...
