---
- hosts: all
  vars:
    db_package: mariadb-server
    db_service: mariadb
    db_users:
      - db_admin
      - db_user
    configure_database_path: /etc/my.cnf
  tasks:
  - name: Create the MariaDB users
    users:
      name: "{{item}}"
    with_items: "{{db_users}}"
    when inventory_hostname in groups['databases']

