---
- hosts: localhost
  tasks:
    - block:
      - name: Copy the config file1
        copy:
          src: /tmp/myapp1.conf
          dest: /etc/myapp1.conf
          owner: student
          mode: 0644

      rescue:
        - name: Copy the config file2
          copy:
            src: /tmp/myapp2.conf
            dest: /etc/myapp2.conf
            owner: student
            mode: 0644
      
      always:
        - debug:
            msg: "This is to be executed always, No matter what!!"
