- name: Play to demo variable scope
  hosts: localhost
  vars:
    var1: value1_from_play
  tasks:
    - name: Task to include the variable file
      include_vars: vars/test.yml
    - name: Task1 which uses the vars
      vars:
        var1: value1_from_task
      debug:
        msg: "The value of var1 is {{var1}}"
