---
- name: Play with a log running task
  hosts: serverb.lab.example.com
  tasks:
  - name: Long task to run on a managed hosts.
    shell: sleep 15 && touch /tmp/task1.done
    async: 20
    poll: 0
  
 # - name: Waiting for task 1 completion.
 #   wait_for: 
 #     path: /tmp/task1.done
   
  - name: Task no. 2
    shell: sleep 2 && touch /tmp/task2.done
  
  - name: Task no. 3
    shell: sleep 2 && touch /tmp/task3.done
