---
- hosts: remote
  vars:
    newusers:
      - name: user1
        pass: redhat
      - name: user2
        pass: ansible
    shell: /bin/bash
  tasks:
  - name: Create new users on remote servers.
    user:
      name: "{{item.name}}"
      password: "{{ item.pass | password_hash('sha512')}}"
      shell: "{{shell}}"
    with_items: "{{newusers}}"

