---
- hosts: localhost
  vars:
    newusers:
      - name: user1
        pass: redhat
      - name: user2
        pass: ansible
    shell: /bin/bash
  tasks:
  - name: Create new users
    user:
      name: "{{item.name}}"
      password: "{{ item.pass | password_hash('sha12')}}"
    with_items: "{{newusers}}"
    no_log: True

