---
- name: Play to demo the value of facts on a delegated host
  hosts: servera.lab.example.com
  tasks:
  - name: Task to run a command on a delegated host.
    debug:
      msg: "Hello this is the value of ansible_fqdn : {{ansible_fqdn}}"
#    delegate_to: localhost
#    delegate_facts: True
