- name: Test play to test CPersist
  hosts: servera.lab.example.com
  gather_facts: no
  tasks:
  - name: Task1 to create file1.
    copy:
      dest: /tmp/test1
      content: "Test data1"
  
  - name: Waiting task
    pause:
      prompt: "Taking a break for 25 seconds"
      seconds: 25

  - name: Task2 to create file2.
    copy:
      dest: /tmp/test2
      content: "Test data2"
